language: swift
osx_image: xcode11.6
xcode_workspace: Chat.xcworkspace
xcode_scheme: Chat
xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone 8
install:
  - bundle install
scripts:
  - fastlane run_all_tests 