language: swift
os: osx
osx_image: xcode11.6
xcode_workspace: Chat.xcworkspace
xcode_scheme: Chat
xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone 8
cache:
  bundler: true
  cocoapods: true
install:
  - bundle install
script:
  - fastlane build_and_test 