setup_travis

default_platform(:ios)

platform :ios do
  before_all do
      cocoapods
  end

  desc "Build and test all app"
  lane :build_and_test do
    scan(
      device: "iPhone 8"
    )
  end

  desc "Build app without testing"
  lane :build_for_testing do
    scan(
      build_for_testing: true,
      device: "iPhone 8"
    )
  end

  desc "Run tests without building"
  lane :run_all_tests do
    scan(
      skip_build: true,
      device: "iPhone 8"
    )
  end
end
